server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  datasource:
    username: doadmin
    password: AVNS_Ab_9vF8e1DIuNhU--Za
    url: jdbc:postgresql://db-hotel-do-user-14565222-0.b.db.ondigitalocean.com:25060/defaultdb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

host: ${HOST:http://localhost}
services:
  notification-url: ${NOTIFICATION_URL:http://NOTIFICATION-SERVICE/notification}

#  notification-url: ${NOTIFICATION_URL:http://NOTIFICATION-SERVICE/notification}

eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA_URI:http://localhost:8761/eureka/}
    instance:
      preferIpAddress: true

jwt:
  secret:
    key:  753778214125442A472D4B6150645367566B59703373367639792F423F452848
  access:
    expiry: 3000000
  refresh:
    expiry: 3000000